### ISSUE TITLE
Error during import

### ISSUE THREAD

**Issue by Glunty** [MrVauxs/pf2e-jb2a-macros#4]
Hello, I got got this error at world start, followed by an error at macro execution because the property version is not defined

Caused by https://github.com/MrVauxs/pf2e-jb2a-macros/blob/16f501f4ffbe74570d87c27993f638e3ef1b4ce0/module/auto-import.js#L14

foundry.js:319 ReferenceError: number is not defined
[Detected 2 packages: pf2e-jb2a-macros, lib-wrapper]
    at auto-import.js:14:9
    at Hooks._call (foundry.js:294:14)
    at Hooks.callAll (foundry.js:253:12)
    at Game.initialize (foundry.js:5419:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511:22)
    at 🎁libWrapperInit (libWrapper-api.js:793:11)

I think 'number' should be with a capital N

**Comment by MrVauxs** [comment]
Harmless, but fixed and will be pushed in 1.8.0.
