### ISSUE TITLE
error message on every chat message

### ISSUE THREAD

**Issue by Ironxxx** [MrVauxs/pf2e-jb2a-macros#9]
Hi,
I get the following error message in the console with every chat message no matter where it's from (I can just type a single word and the error still comes up). Do you have any idea what causes it, it seems to be linked to this mod.

```TypeError: Cannot read properties of null (reading '1')
[Detected 1 package: pf2e-jb2a-macros]
    at module.js:107:105
    at Hooks._call (foundry.js:294:14)
    at Hooks.call (foundry.js:279:33)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:10013:47)
    at async ClientDatabaseBackend._createDocuments (foundry.js:9930:22)
    at async ChatMessagePF2e.createDocuments (document.mjs:338:21)
    at async ChatMessagePF2e.create (document.mjs:439:21)```

**Comment by MrVauxs** [comment]
Will be fixed in [1.8.2](https://github.com/MrVauxs/pf2e-jb2a-macros/releases/tag/1.8.2).
